### ISSUE TITLE
Caching Issue when dataSource changes?

### ISSUE THREAD

**Issue by joncursi** [DaleJefferson/react-native-immutable-listview-datasource#10]
I noticed that when my `dataSource` changes, the immutable ListView is not re-rendering rows as it should be.

Say the initial render contained 8 unique rows. Then the data changed, and now we should replace those 8 rows with 10 newly rendered rows of equally unique data. What happens is that the first 8 rows will NOT re-render, even though the new data is different, but the final 2 rows (numbers 9 and 10) will render (because only 8 were initially rendered). Seems to be a row caching issue?

Is there a better way to set up a row equality check?

```jsx
      dataSource: new ImmutableDataSource({
        rowHasChanged: (r1, r2) => !r1.equals(r2),
      }),
```

When keeping my business logic the same, I tried removing this package and going with vanilla ListView from React Native core and it handled it properly.

```jsx
      dataSource: new ListView.DataSource({
        rowHasChanged: (r1, r2) => r1 !== r2,
      }),
```

**Comment by DaleJefferson** [comment]
The issue was that ListView was doing an equality check at the top level and I was reusing the same instance. This should be fixed in v1.3.1
