### ISSUE TITLE
Invalid prop dataSource of type ImmutableDataSource supplied to ListView

### ISSUE THREAD

**Issue by Rewieer** [DaleJefferson/react-native-immutable-listview-datasource#11]
When using IDS with ListView from react-native, I get this error : `Warning : Failed prop type: Invalid prop dataSource of type ImmutableDataSource supplied to ListView, expected instance of ListViewDataSource`.

**Comment by spencewine** [comment]
Did you ever figure out what was going here?

**Comment by Rewieer** [comment]
Not really tried to solve it, imo inheriting from ListViewDataSource should do the trick.
With flatlist incoming we might have to revise it anyway

**Comment by DaleJefferson** [comment]
I've switched to using FlatList https://facebook.github.io/react-native/docs/flatlist.html
