### ISSUE TITLE
Incompatible with RN 0.31.0

### ISSUE THREAD

**Issue by fabriziomoscon** [DaleJefferson/React-Native-Immutable-ListView-DataSource#3]
It seems like the new version of react-native included some changes that enforce this requirement:
https://github.com/facebook/react-native/blob/bd60d828c5fc9cb066e5f647c87ecd6f70cb63a5/Libraries/CustomComponents/ListView/ListView.js#L131
which has been present for long time in the `ListView`

I am not sure if there is an easy fix to make this module extend `ListViewDataSource` or this is simply not possible anymore.

![screenshot_2016-08-12-14-34-21](https://cloud.githubusercontent.com/assets/721890/17624778/fdb6cdf6-609d-11e6-9639-9cd267f9e8cb.png)

**Comment by fabriziomoscon** [comment]
Actually I noticed that `index.js` version `1.0.0` was extending `ListView.DataSource`

```
/* @flow */

import {ListView} from 'react-native'
import immutable from 'immutable'

export default class ImmutableDataSource extends ListView.DataSource {
    constructor() {
        super({rowHasChanged: immutable.is})
    }

    cloneWithRows(immutableRows) {
        return super.cloneWithRows(immutableRows.toArray())
    }
}
```

so I think the bug has been introduced by the new v `1.1.1` @DaleJefferson 

and I can confirm RN `0.31.0` works with version `1.0.0`

so I think that the improvements of the newer version should be applied keep the extension of `ListView.DataSource`

**Comment by DaleJefferson** [comment]
I've tested v1.2.0 with React Native 0.32.0, you get this proptype warning but everything works as expected.

I guess we can silence the warning like this.

```js
import React, {PropTypes} from 'react'
import {ListView} from 'react-native'
import ImmutableDataSource from 'react-native-immutable-listview-datasource'

ListView.propTypes.dataSource = PropTypes.instanceOf(ImmutableDataSource).isRequired,
```
