### ISSUE TITLE
Immutable `dataSource` fails ListView prop validation

### ISSUE THREAD

**Issue by joncursi** [DaleJefferson/React-Native-Immutable-ListView-DataSource#7]
I am getting error messages in the JS console after integrating this package into my project per the instructions given in the readme:

```
ExceptionsManager.js:82 Warning: Failed prop type: Invalid prop `dataSource` of type `ImmutableDataSource` supplied to `ListView`, expected instance of `ListViewDataSource`.
    in ListView (created by UserAddresses)
```

Is there an additional step I need to take, or is this a bug? Seems like the following validation is failing:

https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js#L134

**Comment by DaleJefferson** [comment]
It's a known issue @joncursi I submitted a PR to React Native but it was rejected, a solution would be to do something like this, I'm thinking about adding this to this package.

```
import {ListView} from 'react-native'

class ImmutableListView extends ListView {}

ImmutableListView.propTypes.dataSource = PropTypes.instanceOf(ImmutableDataSource).isRequired,
```

**Comment by joncursi** [comment]
That worked, thank you!
